"""Planet significations — Saravali (Kalyana Varma, ~800 CE), BPHS (Parashara).
Encodes natural karakatvas, house lordship effects, and sign placements.
"""

# ── Natural Karakatvas (BPHS Ch.10 + Saravali Ch.2) ─────────────────────
KARAKATVA = {
    "Sun": {
        "tel": "సూర్యుడు",
        "body": ["soul","heart","right eye","bones","bile"],
        "signifies": ["father","authority","government","royalty","fame","vitality","ego","leadership"],
        "professions": ["government official","doctor","politician","administrator","CEO"],
        "character": "Strong willpower, leadership, confidence, pride. Desires fame and recognition.",
        "tel_desc": "ఆత్మ కారకుడు — ఆత్మ, పితృ, సత్తా, ప్రభుత్వం, కీర్తి",
    },
    "Moon": {
        "tel": "చంద్రుడు",
        "body": ["mind","blood","left eye","lungs","glands"],
        "signifies": ["mother","emotions","mind","public","water","nurturing","memory","travel"],
        "professions": ["nurse","teacher","public relations","marine","psychology","food industry"],
        "character": "Emotional, intuitive, caring, fluctuating. Strong imagination and public appeal.",
        "tel_desc": "మనో కారకుడు — మాత, మనస్సు, భావోద్వేగాలు, జనాభిమానం",
    },
    "Mars": {
        "tel": "అంగారకుడు",
        "body": ["muscles","blood","bone marrow","energy","injuries"],
        "signifies": ["brothers","courage","land","property","war","surgery","energy","passion"],
        "professions": ["military","surgeon","engineer","athlete","police","real estate"],
        "character": "Courageous, aggressive, energetic, competitive. Direct and action-oriented.",
        "tel_desc": "సోదర కారకుడు — సాహసం, భూమి, శక్తి, యుద్ధం, శస్త్రచికిత్స",
    },
    "Mercury": {
        "tel": "బుధుడు",
        "body": ["nervous system","skin","speech","lungs","hands"],
        "signifies": ["intellect","communication","business","writing","education","trade","analysis"],
        "professions": ["writer","accountant","lawyer","trader","teacher","IT professional","journalist"],
        "character": "Analytical, witty, versatile, communicative. Logical thinker, adapts easily.",
        "tel_desc": "విద్యా కారకుడు — బుద్ధి, వ్యాపారం, వాక్శక్తి, గణితం, వ్రాత",
    },
    "Jupiter": {
        "tel": "గురుడు",
        "body": ["liver","fat","hips","thighs","hearing"],
        "signifies": ["wisdom","children","religion","fortune","guru","expansion","law","philosophy"],
        "professions": ["priest","judge","professor","counselor","banker","philosopher"],
        "character": "Wise, generous, optimistic, righteous. Seeks truth, loves learning, spiritually inclined.",
        "tel_desc": "జ్ఞాన కారకుడు — జ్ఞానం, సంతానం, ధర్మం, సంపద, గురువు",
    },
    "Venus": {
        "tel": "శుక్రుడు",
        "body": ["reproductive system","kidneys","throat","eyes","skin"],
        "signifies": ["wife","love","beauty","arts","luxury","vehicles","pleasures","music"],
        "professions": ["artist","musician","designer","actor","beautician","jeweler","diplomat"],
        "character": "Charming, artistic, romantic, pleasure-loving. Aesthetic sense, social grace.",
        "tel_desc": "కళత్ర కారకుడు — ప్రేమ, కళ, సౌందర్యం, వాహనాలు, ఐశ్వర్యం",
    },
    "Saturn": {
        "tel": "శనిuడు",
        "body": ["legs","teeth","joints","nerves","longevity"],
        "signifies": ["discipline","karma","delays","servants","old age","death","hard work","justice"],
        "professions": ["laborer","miner","ascetic","judge","scientist","engineer","administrator"],
        "character": "Disciplined, patient, hardworking, serious. Learns through hardship. Values justice.",
        "tel_desc": "ఆయుః కారకుడు — కర్మ, క్రమశిక్షణ, ఆలస్యం, సేవకులు, న్యాయం",
    },
    "Rahu": {
        "tel": "రాహువు",
        "body": ["nervous disorders","skin","poison","undiagnosed illness"],
        "signifies": ["foreigners","technology","illusion","ambition","sudden events","unconventional paths"],
        "professions": ["IT","research","foreign trade","aviation","politics","film"],
        "character": "Ambitious, unconventional, obsessive, illusory. Magnifies what it touches.",
        "tel_desc": "మాయ, విదేశాలు, ఆకస్మిక సంఘటనలు, సాంకేతికత",
    },
    "Ketu": {
        "tel": "కేతువు",
        "body": ["spiritual body","ears","wounds","past karma"],
        "signifies": ["moksha","spirituality","detachment","past life","occult","liberation"],
        "professions": ["monk","astrologer","healer","researcher","mystic"],
        "character": "Spiritual, detached, mystical, introspective. Brings sudden separations and insights.",
        "tel_desc": "మోక్ష కారకుడు — ఆధ్యాత్మికత, వైరాగ్యం, పూర్వజన్మ కర్మ",
    },
}

# ── Planet in each house — effects (Saravali Ch.7–15 + BPHS Ch.24–32) ──────
PLANET_IN_HOUSE = {
    "Sun": {
        1: "Strong personality, commanding presence, leadership. Health is good. Self-reliant. (సూర్యుడు లగ్నంలో: ప్రభుత్వ సేవ, ఆత్మవిశ్వాసం)",
        2: "Accumulates wealth through authority. Speech is commanding but harsh at times. Eye issues possible.",
        3: "Courageous, bold communication. Siblings may be powerful. Short journeys favor career.",
        4: "Domestic tension. Father may be strict. Property matters. Heart or chest health.",
        5: "Creative, intelligent children. Government favor. Interest in politics, speculation, education.",
        6: "Defeats enemies easily. Good for medicine, law, service. Health issues: stomach, blood.",
        7: "Spouse may be domineering. Partnership issues. Career in public-facing roles.",
        8: "Hidden knowledge. Longevity issues unless strong. Sudden inheritance or loss.",
        9: "Very fortunate. Righteous, philosophical, excellent father. Fortune comes through dharma.",
        10: "Excellent for career — raj yoga potential. Fame, authority, government employment.",
        11: "Gains through powerful connections. Elder siblings support. Fulfills ambitions.",
        12: "Expenses on status. Foreign connections. Spiritual inclination. Eye health.",
    },
    "Moon": {
        1: "Charming appearance, popular, emotional, maternal instinct. Mind fluctuates like Moon phases.",
        2: "Wealth through public, mother. Sweet speech. Family-oriented. Eating habits important.",
        3: "Courageous but restless mind. Frequent short travels. Communication through emotions.",
        4: "Excellent for mother and home. Strong emotional foundation. Real estate benefits.",
        5: "Romantic, creative, intuitive children. Emotional intelligence. Memory is excellent.",
        6: "Health fluctuates. Service to others emotionally. Enemies through emotional reactions.",
        7: "Attractive, popular spouse. Public dealings. Emotions involved in partnerships.",
        8: "Hidden depths. Occult interests. Mother's health concern. Inheritance through mother.",
        9: "Philosophical emotions. Fortunate through mother, religion. Travel to sacred places.",
        10: "Public career. Fame. Changes in profession. Mother influences career.",
        11: "Gains through public, women. Fulfills desires. Elder sibling is female.",
        12: "Spiritual, reclusive. Hidden emotional world. Foreign settlement. Sleep issues.",
    },
    "Mars": {
        1: "Aggressive, energetic, competitive. Scar on body possible. High physical energy.",
        2: "Harsh speech. Financial ups-downs. Family disputes. Accumulates through hard work.",
        3: "Excellent: courageous, bold, athletic. Brothers are strong. Technical skills.",
        4: "Manglik effects. Home disputes. Property gains through struggle. Real estate profits.",
        5: "Speculative losses possible. Intelligence in technical fields. Sons are athletic.",
        6: "Best placement — destroys enemies, diseases. Surgeon, military, police service.",
        7: "Manglik: spouse issues. Passionate marriage. Partner is energetic/athletic.",
        8: "Long life. Accidents possible. Sudden gains/losses. Inheritance disputes.",
        9: "Dharma through action. Pilgrimage. Religious conflicts. Fortune through effort.",
        10: "Excellent career drive. Engineer, military, sports. Strong ambition for success.",
        11: "Huge gains. Elder brothers are energetic. Profits from real estate/industry.",
        12: "Expenses on pleasures/enemies. Foreign enemies. Hidden conflicts. Hospital stays.",
    },
    "Mercury": {
        1: "Intelligent, witty, communicative. Youthful appearance. Business-minded. Analytical.",
        2: "Eloquent speech. Gains through writing, business. Family is educated. Financial skills.",
        3: "Excellent communication skills. Writing, media, teaching. Siblings are intelligent.",
        4: "Educated in homeland. Logical home environment. Real estate through intellect.",
        5: "Highly intelligent children. Creative writing. Speculative gains through analysis.",
        6: "Excellent for medicine, law, finance. Defeats enemies through wit. Health management.",
        7: "Spouse is intelligent. Partnership in business/writing. Contracts favorable.",
        8: "Research, occult, deep analysis. Longevity through carefulness. Hidden knowledge.",
        9: "Philosophical intellect. Good teacher. Fortune through writing/communication.",
        10: "Career in IT, media, finance, education. Business success. Versatile professional.",
        11: "Gains through communication, business, intellect. Networks are vast.",
        12: "Foreign trade profits. Hidden intellectual pursuits. Spiritual writing.",
    },
    "Jupiter": {
        1: "Wise, learned, generous. Good body (tends to weight). Respected in society. Spiritual.",
        2: "Excellent wealth accumulation. Learned family. Sweet, wise speech. Financial luck.",
        3: "Wisdom in communication. Siblings are fortunate. Learning through short journeys.",
        4: "Home is a center of learning. Excellent for mother. Real estate fortune.",
        5: "Strong children, intelligent and fortunate. Creative, philosophical, speculative gains.",
        6: "Defeats illness through wisdom. Service-oriented. Medical or legal profession.",
        7: "Excellent spouse — wise, fortunate. Business partnerships prosper. Marriage is blissful.",
        8: "Longevity. Hidden wisdom. Inheritance. Occult knowledge. Spiritual transformation.",
        9: "Best placement: Dharmadhipati — maximum fortune, wisdom, spiritual progress.",
        10: "Career in law, education, religion, medicine. Authority. Raj yoga potential.",
        11: "Massive gains. Elder sibling is wise. All ambitions fulfilled. Social connections.",
        12: "Spiritual liberation. Foreign ashram. Expenses on charity. Moksha-oriented life.",
    },
    "Venus": {
        1: "Beautiful, charming, artistic. Loves luxury. Attractive personality. Fond of pleasures.",
        2: "Wealthy family. Beautiful face/voice. Gains through art, luxury goods, beauty industry.",
        3: "Artistic communication. Creative writing, music. Siblings are artistic. Social travels.",
        4: "Beautiful home. Devoted mother. Vehicles, comforts. Real estate profits.",
        5: "Romantic, artistic children. Love affairs. Creative talents prominent. Speculation wins.",
        6: "Health from beauty/luxury imbalance. Gains by serving through art. Enemies may be women.",
        7: "Excellent spouse — beautiful, artistic. Successful partnerships. Marriage is central.",
        8: "Inherited luxuries. Mysterious romantic life. Longevity. Secret love affairs.",
        9: "Fortune through art, luxury, women. Spiritual practices with grace.",
        10: "Career in arts, entertainment, fashion, beauty, luxury. Fame through creative work.",
        11: "Gains from women, art, luxury. Social network through artistic circles.",
        12: "Pleasure-seeking. Foreign luxuries. Bed comforts. Spiritual devotion through art.",
    },
    "Saturn": {
        1: "Serious, disciplined, hardworking. Slow but steady success. Delay in everything but permanent gains.",
        2: "Speech is serious/harsh. Wealth through hard work. Family hardships. Dental issues.",
        3: "Hardworking in communication. Disciplined siblings. Technical writer. Slow but successful.",
        4: "Property through hard work. Mother's health concern. Separation from homeland.",
        5: "Delayed children. Serious intellect. Gains through discipline, research, long-term plans.",
        6: "Excellent: Saturn rules service/discipline — defeats enemies through persistence.",
        7: "Delayed or serious marriage. Spouse is older or disciplined. Partnerships require patience.",
        8: "Very long life. Inheritance disputes. Hidden karmas. Chronic health issues possible.",
        9: "Fortune comes slowly but surely. Disciplined dharma. Father may be strict/absent.",
        10: "Excellent career through hard work — eventual peak success. Government, engineering.",
        11: "Gains come slowly but accumulate enormously. Elder siblings are disciplined.",
        12: "Foreign lands. Spiritual discipline. Isolation for learning. Expenses are controlled.",
    },
    "Rahu": {
        1: "Unconventional personality. Foreign or unusual appearance. Ambitious to the extreme.",
        2: "Unconventional wealth sources. Foreign income. Family may be unusual. Speech is deceptive.",
        3: "Bold, unconventional courage. Media, technology communication. Siblings are unusual.",
        4: "Unusual home situation. Foreign properties. Mother may be different background.",
        5: "Unusual intelligence. Foreign education. Speculation gains/losses. Unconventional children.",
        6: "Excellent — defeats enemies through cunning. Works in research, IT, foreign service.",
        7: "Foreign or unusual spouse. Unconventional partnerships. Business with foreigners.",
        8: "Occult, research, sudden transformation. Hidden gains. Past life karma is intense.",
        9: "Foreign religion or philosophy. Fortune through unconventional paths. Guru is unusual.",
        10: "Career in technology, foreign companies, media, research. Ambition for unusual heights.",
        11: "Massive gains from foreign/technology/unconventional sources. Unique social network.",
        12: "Foreign settlement. Spiritual paths outside mainstream. Hidden vices possible.",
    },
    "Ketu": {
        1: "Spiritual, detached personality. Past life carry-over. Unusual health patterns. Mystical.",
        2: "Detachment from wealth. Speech is unusual/spiritual. Family karma from past lives.",
        3: "Spiritual communication. Detachment from siblings. Writing on spiritual/occult topics.",
        4: "Detachment from home/mother. Foreign homes. Spiritual home environment.",
        5: "Spiritual intelligence. Past life karmic children. Occult, meditation, mantra knowledge.",
        6: "Excellent for healing — fights enemies/disease through spiritual means.",
        7: "Spiritual spouse or unusual marriage. Detachment in partnerships. Karmic relationships.",
        8: "Deepest occult knowledge. Spiritual transformation. Past life debts resolved.",
        9: "Moksha orientation. Spiritual fortune. Detachment from conventional dharma. Guru is rare.",
        10: "Career in spirituality, healing, research, mysticism. Unusual professional path.",
        11: "Gains through spiritual/occult work. Detachment from material gains despite having them.",
        12: "Liberation (moksha) orientation. Foreign spiritual journeys. Final karma resolution.",
    },
}