"""Validation tests for build_plan.md Phase 2's compiled rule content:
planet-in-house (108), house-lord-placement (144), planet-in-sign (108),
and dosha rules (15) -- all generated by app.rules.generators.emit_all and
evaluated through the existing generic v2 evaluator (no new evaluation
logic; this proves the data-driven pipeline actually works end-to-end).
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.derived.factors import build_chart_context
from app.fixtures import list_fixture_ids, load_chart_fixture
from app.rules.generic_evaluator import evaluate_rule_set
from app.rules.loader import load_compiled_rule_packs
from app.rules.schema import Rule

COMPILED_DIR = ROOT / "app" / "rules" / "compiled"


def _context(fixture_id: str = "ajay_kumar"):
    return build_chart_context(load_chart_fixture(fixture_id))


def _by_category(rules: list[Rule], category: str) -> list[Rule]:
    return [r for r in rules if r.category == category]


def test_all_compiled_packs_load_and_validate():
    rules = load_compiled_rule_packs()
    # Grand total drifts as new packs land (Phase 4 added yoga_v2.yaml,
    # nakshatra_v2.yaml, ...) -- rather than hardcode a number that goes
    # stale every time, verify the total equals the sum of each known
    # prefix's own count, and that no rule id is unaccounted for.
    prefix_counts = {
        "PIH-": 108, "LPH-": 144, "PIS-": 108, "DSH-": 15, "YOG-": 18, "NAK-": 27, "DASHA-": 81,
        "MAR-": 40, "CAR-": 30, "REM-": 20,
    }
    for prefix, expected in prefix_counts.items():
        actual = sum(1 for r in rules if r.id.startswith(prefix))
        assert actual == expected, f"{prefix}: expected {expected}, got {actual}"
    assert len(rules) == sum(prefix_counts.values())


def test_no_duplicate_rule_ids_across_all_compiled_packs():
    rules = load_compiled_rule_packs()
    ids = [r.id for r in rules]
    assert len(ids) == len(set(ids)), "duplicate rule id found across compiled packs"


def test_planet_in_house_pack_has_108_active_classical_rules():
    rules = load_compiled_rule_packs(COMPILED_DIR)
    pih = [r for r in rules if r.id.startswith("PIH-")]
    assert len(pih) == 108
    assert all(r.status == "ACTIVE" and r.computation_model == "classical" for r in pih)


def test_lord_placement_pack_has_144_practical_proxy_rules():
    rules = load_compiled_rule_packs(COMPILED_DIR)
    lph = [r for r in rules if r.id.startswith("LPH-")]
    assert len(lph) == 144
    assert all(r.computation_model == "practical_proxy" and r.category == "lord_placement" for r in lph)


def test_planet_in_sign_pack_has_108_practical_proxy_rules():
    rules = load_compiled_rule_packs(COMPILED_DIR)
    pis = [r for r in rules if r.id.startswith("PIS-")]
    assert len(pis) == 108
    assert all(r.computation_model == "practical_proxy" for r in pis)


def test_dosha_pack_has_15_classical_rules():
    rules = load_compiled_rule_packs(COMPILED_DIR)
    dsh = [r for r in rules if r.id.startswith("DSH-")]
    assert len(dsh) == 15
    assert all(r.computation_model == "classical" for r in dsh)


# ── End-to-end evaluation against real chart contexts ─────────────────────
def test_exactly_9_planet_in_house_rules_match_per_fixture():
    """Every planet occupies exactly one house -> exactly 9 of the 108
    PIH rules should match, one per planet, and each should report
    quality=computed (classical rules, no synthesis discount)."""
    rules = [r for r in load_compiled_rule_packs(COMPILED_DIR) if r.id.startswith("PIH-")]
    for fixture_id in list_fixture_ids():
        ctx = _context(fixture_id)
        evaluations = evaluate_rule_set(rules, ctx)
        matched = [e for e in evaluations if e.matched]
        assert len(matched) == 9, f"{fixture_id}: expected 9 matches, got {len(matched)}"
        assert all(e.quality == "computed" for e in matched)
        matched_planets = {e.outputs[0].payload["planet"] for e in matched}
        assert matched_planets == {"Sun", "Moon", "Mars", "Mercury", "Jupiter", "Venus", "Saturn", "Rahu", "Ketu"}
        for evaluation in matched:
            planet = evaluation.outputs[0].payload["planet"]
            house = evaluation.outputs[0].payload["house"]
            assert ctx["chart"][planet]["house"] == house


def test_exactly_12_lord_placement_rules_match_per_fixture():
    """Every one of the 12 houses has exactly one lord, and that lord
    occupies exactly one house -> exactly 12 of the 144 LPH rules should
    match (one per source house), each reporting computed_simplified."""
    rules = [r for r in load_compiled_rule_packs(COMPILED_DIR) if r.id.startswith("LPH-")]
    for fixture_id in list_fixture_ids():
        ctx = _context(fixture_id)
        evaluations = evaluate_rule_set(rules, ctx)
        matched = [e for e in evaluations if e.matched]
        assert len(matched) == 12, f"{fixture_id}: expected 12 matches, got {len(matched)}"
        assert all(e.quality == "computed_simplified" for e in matched)
        matched_sources = {e.outputs[0].payload["source_house"] for e in matched}
        assert matched_sources == set(range(1, 13))
        for evaluation in matched:
            source = evaluation.outputs[0].payload["source_house"]
            dest = evaluation.outputs[0].payload["dest_house"]
            assert ctx["lord_placements"][source]["occupies_house"] == dest


def test_exactly_9_planet_in_sign_rules_match_per_fixture():
    rules = [r for r in load_compiled_rule_packs(COMPILED_DIR) if r.id.startswith("PIS-")]
    for fixture_id in list_fixture_ids():
        ctx = _context(fixture_id)
        evaluations = evaluate_rule_set(rules, ctx)
        matched = [e for e in evaluations if e.matched]
        assert len(matched) == 9, f"{fixture_id}: expected 9 matches, got {len(matched)}"
        assert all(e.quality == "computed_simplified" for e in matched)
        for evaluation in matched:
            planet = evaluation.outputs[0].payload["planet"]
            sign = evaluation.outputs[0].payload["sign"]
            assert ctx["chart"][planet]["sign"] == sign


def test_dosha_rules_agree_with_direct_doshas_dict_for_every_fixture():
    """Cross-check: whatever DSH-001 (mangal dosha present) reports must
    exactly match ctx['doshas']['mangal_dosha']['present'] -- no drift
    between the v2 rule wrapper and the underlying computed truth."""
    rules = [r for r in load_compiled_rule_packs(COMPILED_DIR) if r.id.startswith("DSH-")]
    for fixture_id in list_fixture_ids():
        ctx = _context(fixture_id)
        evaluations = {e.rule_id: e for e in evaluate_rule_set(rules, ctx)}
        assert evaluations["DSH-001"].matched == ctx["doshas"]["mangal_dosha"]["present"]
        assert evaluations["DSH-007"].matched == ctx["doshas"]["pitru_dosha"]["present"]
        assert evaluations["DSH-009"].matched == ctx["doshas"]["guru_chandala"]["present"]
        assert evaluations["DSH-013"].matched == ctx["doshas"]["papakartari"]["present"]
        assert evaluations["DSH-015"].matched == ctx["transits"]["saturn_assessment"]["sade_sati"]["active"]
        for evaluation in evaluations.values():
            assert evaluation.quality != "data_gap"


def test_marriage_pack_has_40_practical_proxy_rules():
    rules = load_compiled_rule_packs(COMPILED_DIR)
    mar = [r for r in rules if r.id.startswith("MAR-")]
    assert len(mar) == 40
    assert all(r.category == "marriage" and r.status == "ACTIVE" for r in mar)


def test_career_pack_has_30_rules_with_expected_computation_models():
    rules = load_compiled_rule_packs(COMPILED_DIR)
    car = [r for r in rules if r.id.startswith("CAR-")]
    assert len(car) == 30
    assert all(r.category == "career" for r in car)
    lordis = [r for r in car if r.id.startswith("CAR-LORDIS-")]
    assert len(lordis) == 7 and all(r.computation_model == "classical" for r in lordis)


def test_remedy_pack_has_20_classical_rules():
    rules = load_compiled_rule_packs(COMPILED_DIR)
    rem = [r for r in rules if r.id.startswith("REM-")]
    assert len(rem) == 20
    assert all(r.category == "remedy" and r.computation_model == "classical" for r in rem)


def test_remedy_nogem_rules_agree_with_direct_remedies_dict_for_every_fixture():
    """Safety-critical cross-check: REM-NOGEM-<CODE> must exactly match
    ctx['remedies']['planets'][planet]['gemstone_contraindicated'] -- no
    drift between the v2 rule wrapper and the underlying safety gate."""
    rules = [r for r in load_compiled_rule_packs(COMPILED_DIR) if r.id.startswith("REM-NOGEM-")]
    code_to_planet = {"SUN": "Sun", "MOO": "Moon", "MAR": "Mars", "MER": "Mercury", "JUP": "Jupiter",
                       "VEN": "Venus", "SAT": "Saturn", "RAH": "Rahu", "KET": "Ketu"}
    for fixture_id in list_fixture_ids():
        ctx = _context(fixture_id)
        evaluations = {e.rule_id: e for e in evaluate_rule_set(rules, ctx)}
        for rule in rules:
            code = rule.id.replace("REM-NOGEM-", "")
            planet = code_to_planet[code]
            expected = ctx["remedies"]["planets"][planet]["gemstone_contraindicated"]
            assert evaluations[rule.id].matched == expected, f"{fixture_id}:{rule.id}"


if __name__ == "__main__":
    import traceback

    tests = [obj for name, obj in list(globals().items()) if name.startswith("test_")]
    failed = 0
    for t in tests:
        try:
            t()
            print(f"[PASS] {t.__name__}")
        except Exception:
            failed += 1
            print(f"[FAIL] {t.__name__}")
            traceback.print_exc()
    print(f"\n{len(tests) - failed}/{len(tests)} passed")
    raise SystemExit(1 if failed else 0)
